---
title: "Data documentation"
author: "Dr. Chris Moreh<br> York St. John University"
date: "`r Sys.Date()`"
output:
  rmdformats::readthedown:
    highlight: tango
---

```{r setup, include=FALSE}
## Global options
knitr::opts_chunk$set(cache = TRUE)
```

## Description of datasets

The datasets used in this course and available for download from the course website are the following:

+------------+----------------------------------+--------+---------+---------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------+
| File name  | Original name                    | Type   | Version | Survey                                                                                | Links                                                                                                             |
+============+==================================+========+=========+=======================================================================================+===================================================================================================================+
| eb89.1     | ZA6963_v1-0-0                    | .dta \ | 1.0.0   | Eurobarometer; 89.1 (March 2018)                                                      | [Source](https://search.gesis.org/research_data/ZA6963 "GESIS")\                                                  |
|            |                                  | .sav   |         |                                                                                       | [Questionnaire](https://cgmoreh.github.io/SSC7001M/data/ZA6963_q_gb.pdf "Download PDF")\                          |
|            |                                  |        |         |                                                                                       | Codebook                                                                                                          |
+------------+----------------------------------+--------+---------+---------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------+
| ess9       | ESS9e03_1                        | .dta \ | 3.1     | European Social Survey; Integrated file, Round 9 (2018)                               | [Source](https://www.europeansocialsurvey.org/download.html?file=ESS9e03_1&y=2018 "ESS website")\                 |
|            |                                  | .sav   |         |                                                                                       | [Questionnaire](https://cgmoreh.github.io/SSC7001M/data/ESS9_source_questionnaires.pdf "Download PDF")\           |
|            |                                  |        |         |                                                                                       | Codebook                                                                                                          |
+------------+----------------------------------+--------+---------+---------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------+
| evs5       | ZA7500_v4-0-0                    | .dta \ | 4.0.0   | European Values Study; Wave 5 (2017-2020)                                             | [Source](https://search.gesis.org/research_data/ZA7500 "GESIS")\                                                  |
|            |                                  | .sav   |         |                                                                                       | [Questionnaire](https://cgmoreh.github.io/SSC7001M/data/ZA7500_q_gb.pdf "Download PDF")\                          |
|            |                                  |        |         |                                                                                       | Codebook                                                                                                          |
+------------+----------------------------------+--------+---------+---------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------+
| EUinUK2018 | EUinUK2018_Polish                | .dta   | \-      | Survey data collected by McGhee and Moreh (2018), ESRC Centre for Population Change   | Source\                                                                                                           |
|            |                                  |        |         |                                                                                       | [Questionnaire](https://cgmoreh.github.io/SSC7001M/data/EUinUK 2018 Questionnaire.pdf "Download PDF")\            |
|            |                                  |        |         |                                                                                       | Codebook                                                                                                          |
+------------+----------------------------------+--------+---------+---------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------+
| LaddLenz   | LaddLenz                         | .dta   | \-      | Replication data for Ladd and Lenz (2009), based on British Election Panel Study data | [Source](https://dataverse.harvard.edu/dataset.xhtml?persistentId=hdl:1902.1/16077 "Hainmueller 2011 Dataverse")\ |
|            |                                  |        |         |                                                                                       | Questionnaire\                                                                                                    |
|            |                                  |        |         |                                                                                       | Codebook                                                                                                          |
+------------+----------------------------------+--------+---------+---------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------+
| osterman   | Replication_data_ESS1-9_20201113 | .dta   | \-      | Replication data for Österman (2020), based on European Social Survey Rounds 1-9 data | [Source](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/RCSCDA "Osterman Dataverse")\   |
|            |                                  |        |         |                                                                                       | Questionnaire\                                                                                                    |
|            |                                  |        |         |                                                                                       | Codebook                                                                                                          |
+------------+----------------------------------+--------+---------+---------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------+
